export type LessonTopic={title:string;content:string};
export function lessonTopics(subject:string):LessonTopic[]{
 const key=subject.toLocaleLowerCase('pt-BR');
 if(key.includes('banco de dados'))return [{title:'Modelagem de dados',content:'Bancos relacionais organizam informações em tabelas. Entidades representam objetos do domínio; atributos descrevem essas entidades e chaves identificam cada registro.'},{title:'Relacionamentos e normalização',content:'Chaves estrangeiras conectam tabelas. Normalizar separa fatos independentes, reduz duplicação e ajuda a manter os dados consistentes.'},{title:'Consultas SQL',content:'SELECT consulta dados, WHERE filtra linhas e ORDER BY ordena resultados. INSERT, UPDATE e DELETE alteram registros.'}];
 if(key.includes('biologia'))return [{title:'Célula e organização da vida',content:'A célula é a unidade estrutural e funcional dos seres vivos. Células procariontes não têm núcleo delimitado; eucariontes possuem núcleo e organelas.'},{title:'Ecossistemas e relações',content:'Ecossistemas reúnem seres vivos e fatores físicos. Cadeias e teias alimentares mostram como matéria e energia circulam entre organismos.'},{title:'Genética e biodiversidade',content:'O DNA guarda informação hereditária. Variações genéticas e ambientais contribuem para a diversidade observada nas populações.'}];
 if(key.includes('física'))return [{title:'Grandezas e medidas',content:'Grandezas físicas são expressas por número e unidade. O Sistema Internacional padroniza medidas para permitir comparação e comunicação.'},{title:'Movimento',content:'Velocidade descreve a variação da posição no tempo; aceleração descreve a variação da velocidade. Gráficos ajudam a interpretar esses movimentos.'},{title:'Forças e energia',content:'Forças podem alterar o movimento ou deformar objetos. O trabalho de uma força transfere energia, que pode mudar de forma e se conservar.'}];
 if(key.includes('química'))return [{title:'Matéria e transformações',content:'A matéria possui propriedades observáveis e pode sofrer transformações físicas ou químicas. Em reações químicas, os átomos se reorganizam.'},{title:'Átomos e ligações',content:'Prótons, nêutrons e elétrons compõem os átomos. Ligações químicas explicam como átomos se agrupam e as propriedades das substâncias.'},{title:'Reações químicas',content:'Equações representam reagentes e produtos. Balanceá-las respeita a conservação dos átomos de cada elemento.'}];
 if(key.includes('matemática')||key.includes('estatística'))return [{title:'Representar o problema',content:'Identifique as informações conhecidas, a pergunta e as relações entre as quantidades. Tabelas, expressões e gráficos ajudam a organizar os dados.'},{title:'Estratégias e cálculo',content:'Escolha operações e propriedades adequadas, registre as etapas e mantenha as unidades. Uma estimativa ajuda a verificar se o resultado faz sentido.'},{title:'Interpretar resultados',content:'Explique o que o resultado significa no contexto. Em estatística, observe medidas de centro e dispersão antes de tirar conclusões.'}];
 if(key.includes('programação')||key.includes('desenvolvimento')||key.includes('engenharia de software'))return [{title:'Decompor o problema',content:'Descreva entradas, saídas e regras do problema. Dividir o trabalho em partes menores torna a solução mais fácil de planejar e revisar.'},{title:'Construir a solução',content:'Algoritmos descrevem passos para resolver problemas. Variáveis armazenam valores, condicionais escolhem caminhos e laços repetem tarefas.'},{title:'Testar e melhorar',content:'Teste casos comuns e limites. Depuração, revisão e testes ajudam a localizar erros e a manter o comportamento correto.'}];
 if(key.includes('sociologia'))return [{title:'Sociedade e cultura',content:'Normas, valores e instituições organizam a vida coletiva. A sociologia investiga como essas relações se formam e se transformam.'},{title:'Grupos e desigualdades',content:'Classe, raça, gênero e território podem influenciar oportunidades. Analisar estruturas ajuda a entender desigualdades além de casos individuais.'},{title:'Pesquisa social',content:'Entrevistas, questionários e observação produzem evidências diferentes. Consentimento e interpretação cuidadosa são essenciais.'}];
 if(key.includes('história'))return [{title:'Fontes históricas',content:'Fontes materiais, escritas, visuais e orais ajudam a investigar o passado. Toda fonte tem contexto, autoria e limites de interpretação.'},{title:'Mudanças e permanências',content:'Processos históricos combinam rupturas, continuidades e conflitos. Comparar grupos revela que as mudanças não afetam todos igualmente.'},{title:'Memória e cidadania',content:'Memórias coletivas influenciam identidades e disputas por reconhecimento. Diferentes narrativas ajudam a interpretar questões do presente.'}];
 if(key.includes('geografia'))return [{title:'Espaço geográfico',content:'O espaço geográfico é produzido pelas relações entre sociedade e natureza ao longo do tempo. Paisagens registram marcas dessas relações.'},{title:'Mapas e escalas',content:'Mapas representam espaços com projeções, símbolos e escala. A escala relaciona a distância representada à distância real.'},{title:'População e território',content:'Distribuição, migração e urbanização transformam territórios e influenciam o acesso a moradia, mobilidade e serviços.'}];
 if(key.includes('filosofia'))return [{title:'Perguntas filosóficas',content:'A filosofia investiga ideias e pressupostos por meio de perguntas, análise crítica e argumentos justificados.'},{title:'Ética e convivência',content:'A ética examina como agir e conviver. Teorias diferentes consideram consequências, deveres e virtudes diante de dilemas.'},{title:'Argumentação crítica',content:'Identificar premissas, evidências e conclusões ajuda a avaliar argumentos e a reconhecer generalizações ou falácias.'}];
 if(key.includes('inglês'))return [{title:'Leitura pelo contexto',content:'Observe título, imagens, cognatos e gênero textual antes de traduzir. O contexto ajuda a inferir palavras desconhecidas.'},{title:'Vocabulário em uso',content:'Aprenda palavras em expressões e frases reais. Encontrá-las em diferentes contextos ajuda a fixar seus significados.'},{title:'Comunicação',content:'Considere público, propósito e situação. Organize as ideias, use conectores e revise se a mensagem está clara.'}];
 if(key.includes('língua portuguesa'))return [{title:'Leitura e interpretação',content:'Identifique tema, propósito, público e ponto de vista. Relacione informações explícitas às pistas que permitem inferir sentidos.'},{title:'Gêneros e argumentação',content:'Gêneros atendem a diferentes propósitos sociais. Uma argumentação consistente apresenta tese, razões e evidências pertinentes.'},{title:'Produção e revisão',content:'Planeje, escreva e revise. Verifique progressão de ideias, coesão, clareza e adequação ao gênero.'}];
 if(key.includes('sistemas operacionais'))return [{title:'Processos e memória',content:'O sistema operacional coordena processos e distribui recursos. Escalonamento e memória virtual ajudam a executar programas.'},{title:'Arquivos e permissões',content:'Sistemas de arquivos organizam dados em diretórios. Permissões definem quem pode ler, alterar ou executar recursos.'},{title:'Terminal e serviços',content:'Comandos de terminal permitem navegar e automatizar tarefas. Serviços executam funções em segundo plano.'}];
 return [{title:'Conceitos fundamentais',content:`Esta unidade apresenta ideias centrais de ${subject}. Identifique conceitos e relacione-os ao que você já conhece.`},{title:'Aplicações e exemplos',content:`Observe como ${subject} aparece em situações reais. Compare exemplos e explique o raciocínio por trás de cada solução.`},{title:'Prática e revisão',content:`Retome os conceitos de ${subject} com exercícios e perguntas próprias. Registre dúvidas para orientar seus próximos estudos.`}];
}
