import './styles.css';
import './course.css';
import { lessonTopics } from './course-content.js';
import { addContribution, readContributions } from './contributions.js';
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));

const lists={
  '1º ano':['Banco de dados I','Biologia 1','Biologia 2-ESG-Environment, Social and Governance','Desenvolvimento I','Filosofia','Física','Geografia','História','Inglês','Língua Portuguesa 2-Chefia e Liderança','Língua Portuguesa I','Matemática 1','Matemática 2-Lógica de Programação','Programação Orientada a Objetos','Química','Sistemas Operacionais'],
  '2º ano':['Banco de dados I','Biologia 1','Biologia 2-ESG-Environment, Social and Governance','Desenvolvimento I','Filosofia','Física','Geografia','História','Inglês','Língua Portuguesa 2-Chefia e Liderança','Língua Portuguesa I','Matemática 1','Matemática 2-Lógica de Programação','Programação Orientada a Objetos','Química','Sistemas Operacionais'],
  '3º ano':['Banco de dados','Desenvolvimento','Desenvolvimento Aplicação Dinâmica','Desenvolvimento de Aplicativo Móvel','Desenvolvimento e Operações Ágeis','Engenharia de Software','Estatística','Inglês','Língua Portuguesa','Matemática','Sociologia','Sociologia 2-Interação Humano-Computador']
};
let year='Todos os anos';let query='';
function render(){const entries=Object.entries(lists).flatMap(([courseYear,names])=>names.map((name,index)=>({name,year:courseYear,index}))).filter(item=>(year==='Todos os anos'||item.year===year)&&item.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));document.querySelector('#root')!.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">G</span><span><strong>GerminaWiki</strong><small>Seu espaço de aprendizagem</small></span></div><div class="side-caption">ENSINO MÉDIO</div><nav class="year-nav">${['Todos os anos',...Object.keys(lists)].map((item,index)=>`<button class="year-button ${year===item?'active':''}" data-year="${item}"><span>${index?'0'+index:'▦'}</span>${item}</button>`).join('')}</nav><div class="sidebar-note"><strong>Conhecimento que cresce junto.</strong><small>Explore as disciplinas do Ensino Médio.</small></div><div class="sidebar-footer">Biblioteca Germinare</div></aside><main class="main"><header class="topbar"><div class="breadcrumbs">Início <span>/</span> <strong>Disciplinas</strong></div><label class="search"><span>⌕</span><input id="search" placeholder="Buscar uma matéria..." value="${query}" aria-label="Buscar uma matéria"/><kbd>/</kbd></label></header><section class="content"><div class="welcome"><div><div class="eyebrow">BIBLIOTECA DE CONTEÚDOS</div><h1>Aprender conecta<br/><em>novas ideias.</em></h1><p>Encontre suas disciplinas e explore novos conhecimentos.</p></div><div class="welcome-art"><span>G</span><i>✳</i></div></div><div class="section-heading"><div><div class="eyebrow">SUA JORNADA</div><h2>Disciplinas <span>${entries.length}</span></h2></div><select id="year-select"><option>Todos os anos</option>${Object.keys(lists).map(item=>`<option ${year===item?'selected':''}>${item}</option>`).join('')}</select></div><div class="subject-grid">${entries.map(item=>`<button class="subject-card" data-course="${item.name}" data-course-year="${item.year}"><span class="subject-icon">✧</span><span class="subject-area">${item.year}</span><strong>${item.name}</strong><span class="open-label">Abrir matéria →</span></button>`).join('')||'<div class="empty">Nenhuma matéria encontrada.</div>'}</div></section></main></div>`;document.querySelectorAll<HTMLButtonElement>('[data-year]').forEach(button=>button.onclick=()=>{year=button.dataset.year!;render()});document.querySelector<HTMLSelectElement>('#year-select')!.onchange=event=>{year=(event.target as HTMLSelectElement).value;render()};document.querySelector<HTMLInputElement>('#search')!.oninput=event=>{query=(event.target as HTMLInputElement).value;const cursor=query.length;render();const input=document.querySelector<HTMLInputElement>('#search')!;input.focus();input.setSelectionRange(cursor,cursor)};}
render();
function openCourse(title:string,courseYear:string){const topics=lessonTopics(title);document.querySelector('#root')!.innerHTML=`<div class="app-shell"><aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">G</span><span><strong>GerminaWiki</strong><small>Seu espaço de aprendizagem</small></span></a><div class="side-caption">${courseYear.toUpperCase()}</div><nav class="topic-nav">${topics.map((topic,index)=>`<a href="#topic-${index}">${String(index+1).padStart(2,'0')} · ${topic.title}</a>`).join('')}</nav><div class="sidebar-footer">Biblioteca Germinare</div></aside><main class="main"><header class="topbar"><button id="go-home" class="breadcrumb-button">← Disciplinas</button><span class="breadcrumbs">${courseYear} / ${title}</span></header><article class="course-page"><div class="eyebrow">${courseYear} · MATERIAL DE ESTUDO</div><h1>${title}</h1><p class="course-summary">Explore os conceitos desta matéria organizados em subtópicos.</p><div class="course-content">${topics.map((topic,index)=>`<section class="topic-section" id="topic-${index}"><div class="topic-kicker">SUBTÓPICO ${String(index+1).padStart(2,'0')}</div><h2>${topic.title}</h2><p>${topic.content}</p><aside class="study-tip"><strong>Para refletir</strong><span>Como você explicaria essa ideia com um exemplo?</span></aside></section>`).join('')}</div><section class="contributions-list"><div class="topic-kicker">APRENDIZAGEM COLABORATIVA</div><h2>Contribuições da turma</h2><p>Compartilhe exemplos e anotações para complementar o estudo.</p>${readContributions(courseYear,title).map(item=>`<article class="contribution-card"><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.body)}</p><small>Contribuição local · ${new Date(item.createdAt).toLocaleDateString('pt-BR')}</small></article>`).join('')||'<p class="empty-inline">Ainda não há contribuições.</p>'}<button id="open-contribution" class="secondary-button">＋ Adicionar conteúdo</button></section></article></main></div><dialog id="contribution-dialog" class="contribution-dialog"><form id="contribution-form" data-subject="${title}" data-year="${courseYear}"><button type="button" id="close-contribution" class="close-button">×</button><h2>Contribua com esta matéria</h2><label>Título<input name="title" maxlength="90" required></label><label>Conteúdo<textarea name="body" rows="5" maxlength="3000" required></textarea></label><small>Esta contribuição fica salva neste navegador.</small><div class="dialog-actions"><button type="button" id="cancel-contribution" class="secondary-button">Cancelar</button><button type="submit" class="primary-button">Salvar</button></div></form></dialog>`;document.querySelector('#go-home')?.addEventListener('click',()=>render());window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-course]');if(button)openCourse(button.dataset.course!,button.dataset.courseYear!);});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.querySelector('#go-home'))render();});
