import './styles.css';
import './course.css';
import { lessonTopics } from './course-content.js';
import { addContribution, readContributions } from './contributions.js';
import { findSubjectPage, hasApiSession, publishContribution, signIn, type RemotePage } from './services/backend-api.js';

const lists={
  '1º ano':['Banco de dados I','Biologia 1','Biologia 2-ESG-Environment, Social and Governance','Desenvolvimento I','Filosofia','Física','Geografia','História','Inglês','Língua Portuguesa 2-Chefia e Liderança','Língua Portuguesa I','Matemática 1','Matemática 2-Lógica de Programação','Programação Orientada a Objetos','Química','Sistemas Operacionais'],
  '2º ano':['Banco de dados I','Biologia 1','Biologia 2-ESG-Environment, Social and Governance','Desenvolvimento I','Filosofia','Física','Geografia','História','Inglês','Língua Portuguesa 2-Chefia e Liderança','Língua Portuguesa I','Matemática 1','Matemática 2-Lógica de Programação','Programação Orientada a Objetos','Química','Sistemas Operacionais'],
  '3º ano':['Banco de dados','Desenvolvimento','Desenvolvimento Aplicação Dinâmica','Desenvolvimento de Aplicativo Móvel','Desenvolvimento e Operações Ágeis','Engenharia de Software','Estatística','Inglês','Língua Portuguesa','Matemática','Sociologia','Sociologia 2-Interação Humano-Computador']
};
type Contribution={title:string;body:string;createdAt:string};
let year='Todos os anos';let query='';let selected:{title:string;year:string}|null=null;let remotePage:RemotePage|null=null;let notice='';
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
function courses(){return Object.entries(lists).flatMap(([courseYear,names])=>names.map(name=>({name,year:courseYear}))).filter(item=>(year==='Todos os anos'||item.year===year)&&item.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));}
function render(){const entries=courses();document.querySelector('#root')!.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">G</span><span><strong>GerminaWiki</strong><small>Seu espaço de aprendizagem</small></span></div><div class="side-caption">ENSINO MÉDIO</div><nav class="year-nav">${['Todos os anos',...Object.keys(lists)].map((item,index)=>`<button class="year-button ${year===item?'active':''}" data-year="${esc(item)}"><span>${index?'0'+index:'▦'}</span>${esc(item)}</button>`).join('')}</nav><div class="sidebar-note"><strong>Conhecimento que cresce junto.</strong><small>Explore as disciplinas do Ensino Médio.</small></div><div class="sidebar-footer">Biblioteca Germinare</div></aside><main class="main"><header class="topbar"><div class="breadcrumbs">Início <span>/</span> <strong>${selected?esc(selected.title):'Disciplinas'}</strong></div><div class="top-actions"><label class="search"><span>⌕</span><input id="search" placeholder="Buscar uma matéria..." value="${esc(query)}" aria-label="Buscar uma matéria"/><kbd>/</kbd></label><button id="api-session" class="secondary-button">${hasApiSession()?'API conectada':'Conectar à API'}</button></div></header>${selected?renderLesson(selected):renderCatalog(entries)}</main></div>${renderLoginDialog()}${renderContributionDialog()}${notice?`<div class="toast" role="status">${esc(notice)}</div>`:''}`;bind();}
function renderCatalog(entries:{name:string;year:string}[]){return`<section class="content"><div class="welcome"><div><div class="eyebrow">BIBLIOTECA DE CONTEÚDOS</div><h1>Aprender conecta<br/><em>novas ideias.</em></h1><p>Encontre suas disciplinas e explore novos conhecimentos.</p></div><div class="welcome-art"><span>G</span><i>✳</i></div></div><div class="section-heading"><div><div class="eyebrow">SUA JORNADA</div><h2>Disciplinas <span>${entries.length}</span></h2></div><select id="year-select"><option ${year==='Todos os anos'?'selected':''}>Todos os anos</option>${Object.keys(lists).map(item=>`<option ${year===item?'selected':''}>${item}</option>`).join('')}</select></div><div class="subject-grid">${entries.map((item,index)=>`<button class="subject-card" data-course="${esc(item.name)}" data-course-year="${esc(item.year)}"><span class="subject-icon">${['✧','◉','⌘','∿','✳','◎'][index%6]}</span><span class="subject-area">${esc(item.year)}</span><strong>${esc(item.name)}</strong><span class="open-label">Abrir matéria →</span></button>`).join('')||'<div class="empty">Nenhuma matéria encontrada.</div>'}</div></section>`;}
function renderLesson(course:{title:string;year:string}){const topics=lessonTopics(course.title);const contributions=readContributions(course.year,course.title);const remoteText=remotePage?.content.split(/\n{2,}/).map(paragraph=>`<p>${esc(paragraph.replace(/^#+\s*/,''))}</p>`).join('')??'';return`<article class="course-page"><div class="course-heading"><div class="eyebrow">${esc(course.year)} · MATERIAL DE ESTUDO</div><h1>${esc(course.title)}</h1><p class="course-summary">Conteúdo organizado por subtópicos. ${remotePage?'Página sincronizada com a API GerminaWiki.':'Conteúdo introdutório disponível para começar a estudar.'}</p><button id="go-home" class="breadcrumb-button">← Voltar às disciplinas</button></div><div class="course-layout"><nav class="topic-nav"><div class="panel-title">NESTA MATÉRIA</div>${topics.map((topic,index)=>`<a href="#topic-${index}">${String(index+1).padStart(2,'0')} · ${esc(topic.title)}</a>`).join('')}<a href="#contributions">＋ Contribuições <b>${contributions.length}</b></a></nav><div class="course-content">${remotePage?`<section class="remote-content"><div class="topic-kicker">CONTEÚDO DO WORKSPACE</div>${remoteText}</section>`:''}${topics.map((topic,index)=>`<section class="topic-section" id="topic-${index}"><div class="topic-kicker">SUBTÓPICO ${String(index+1).padStart(2,'0')}</div><h2>${esc(topic.title)}</h2><p>${esc(topic.content)}</p><aside class="study-tip"><strong>Para refletir</strong><span>Como você explicaria essa ideia com um exemplo?</span></aside></section>`).join('')}<section id="contributions" class="contributions-list"><div class="topic-kicker">APRENDIZAGEM COLABORATIVA</div><h2>Contribuições da turma</h2><p>Envie uma anotação ou exemplo. Com uma página correspondente na API, a contribuição também será publicada como comentário da matéria.</p>${contributions.map(item=>`<article class="contribution-card"><h3>${esc(item.title)}</h3><p>${esc(item.body).replace(/\n/g,'<br/>')}</p><small>Salvo neste navegador · ${new Date(item.createdAt).toLocaleDateString('pt-BR')}</small></article>`).join('')||'<p class="empty-inline">Ainda não há contribuições.</p>'}<button id="open-contribution" class="secondary-button">＋ Adicionar conteúdo</button></section></div></div></article>`;}
function renderLoginDialog(){return`<dialog id="login-dialog" class="contribution-dialog"><form id="login-form"><button type="button" class="close-button" data-close-dialog="login-dialog">×</button><h2>Conectar ao GerminaWiki</h2><p>Entre com sua conta para carregar páginas e publicar contribuições na API.</p><label>E-mail<input type="email" name="email" autocomplete="username" required></label><label>Senha<input type="password" name="password" autocomplete="current-password" required></label><div id="login-error" role="alert"></div><div class="dialog-actions"><button type="button" class="secondary-button" data-close-dialog="login-dialog">Cancelar</button><button class="primary-button" type="submit">Entrar</button></div></form></dialog>`;}
function renderContributionDialog(){return`<dialog id="contribution-dialog" class="contribution-dialog"><form id="contribution-form"><button type="button" class="close-button" data-close-dialog="contribution-dialog">×</button><h2>Contribua com esta matéria</h2><label>Título<input name="title" maxlength="90" required></label><label>Conteúdo<textarea name="body" rows="5" maxlength="3000" required></textarea></label><small>Será salvo neste navegador e, quando houver página correspondente na API, enviado também ao backend.</small><div class="dialog-actions"><button type="button" class="secondary-button" data-close-dialog="contribution-dialog">Cancelar</button><button type="submit" class="primary-button">Salvar contribuição</button></div></form></dialog>`;}
function bind(){document.querySelectorAll<HTMLButtonElement>('[data-year]').forEach(button=>button.onclick=()=>{year=button.dataset.year!;selected=null;render()});document.querySelector<HTMLSelectElement>('#year-select')?.addEventListener('change',event=>{year=(event.target as HTMLSelectElement).value;render()});document.querySelector<HTMLInputElement>('#search')?.addEventListener('input',event=>{query=(event.target as HTMLInputElement).value;const position=query.length;render();const input=document.querySelector<HTMLInputElement>('#search')!;input.focus();input.setSelectionRange(position,position)});document.querySelectorAll<HTMLButtonElement>('[data-course]').forEach(button=>button.onclick=()=>{void openCourse(button.dataset.course!,button.dataset.courseYear!)});document.querySelector('#go-home')?.addEventListener('click',()=>{selected=null;remotePage=null;render()});document.querySelector('#api-session')?.addEventListener('click',()=>document.querySelector<HTMLDialogElement>('#login-dialog')?.showModal());document.querySelectorAll<HTMLElement>('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>document.querySelector<HTMLDialogElement>(`#${button.dataset.closeDialog}`)?.close()));document.querySelector('#open-contribution')?.addEventListener('click',()=>document.querySelector<HTMLDialogElement>('#contribution-dialog')?.showModal());document.querySelector<HTMLFormElement>('#login-form')?.addEventListener('submit',event=>{void login(event)});document.querySelector<HTMLFormElement>('#contribution-form')?.addEventListener('submit',event=>{void contribute(event)});}
async function openCourse(title:string,courseYear:string){selected={title,year:courseYear};remotePage=null;if(hasApiSession()){try{remotePage=await findSubjectPage(title);}catch{notice='A API não respondeu; exibindo o material local.';}}render();window.scrollTo({top:0,behavior:'smooth'});}
async function login(event:SubmitEvent){event.preventDefault();const form=event.currentTarget as HTMLFormElement;const data=new FormData(form);try{await signIn(String(data.get('email')),String(data.get('password')));document.querySelector<HTMLDialogElement>('#login-dialog')?.close();notice='Sessão conectada à API.';if(selected)await openCourse(selected.title,selected.year);else render();}catch(error){document.querySelector('#login-error')!.textContent=error instanceof Error?error.message:'Falha ao entrar.';}}
async function contribute(event:SubmitEvent){event.preventDefault();if(!selected)return;const form=event.currentTarget as HTMLFormElement;const data=new FormData(form);const title=String(data.get('title')??'').trim();const body=String(data.get('body')??'').trim();if(title.length<3||body.length<10){notice='Inclua um título e pelo menos 10 caracteres.';render();return;}try{if(remotePage&&hasApiSession())await publishContribution(remotePage.id,`**${title}**\n\n${body}`);addContribution(selected.year,selected.title,{title,body,createdAt:new Date().toISOString()});document.querySelector<HTMLDialogElement>('#contribution-dialog')?.close();notice=remotePage?'Contribuição salva e enviada à API.':'Contribuição salva neste navegador. Esta matéria ainda não tem uma página correspondente na API.';render();}catch(error){notice=error instanceof Error?error.message:'Não foi possível enviar à API.';render();}}
document.addEventListener('keydown',event=>{if(event.key==='/'&&!(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement)){event.preventDefault();document.querySelector<HTMLInputElement>('#search')?.focus();}});
render();
